services:
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 80:80
    restart: always

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - IMAGE_UPLOAD_KEY=269c080126a91ac7b6f29b286d9df9c1
      - IMAGE_UPLOAD_URL=https://api.imgbb.com/1/upload
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - PG_DATA=/pgdata
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/pgdata