version: "3.8"

services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend/src:/app/backend/src
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      PG_DATA: /pgdata
      POSTGRES_DB: appic
      POSTGRES_USER: appic_user
      POSTGRES_PASSWORD: appic_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: